version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: make unittest
          name: Run unit tests
workflows:
  build_test:
    jobs:
      - build_and_test
