version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  install-deps:
    steps:
      - checkout
      - node/install-packages:
          override-ci-command: npm install --dev
      - run: node --version
workflows:
  test_my_app:
    jobs:
      - install-deps

