name: continuous_integration
on:
  push:
jobs:
  deploy:
    name: CI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm

      - name: Install dependencies
        run: |
          npm i
          ln -s ./node_modules/.bin/esbuild ./esbuild

      - name: Run unit tests
        run: |
          make unittest

      - name: Configure AWS credentials for Sandbox Gamma
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::192591144062:role/github_oidc
          aws-region: ap-southeast-2

      - name: Deploy infrastructure
        run: |
          make deploy

      - name: Run full test suite
        run: |
          make test
